### ISSUE TITLE
Only one Hecke operator?

### ISSUE THREAD

**Issue by jvoight** [assaferan/ModFrmAlg#22]
Sometimes the user might be under heavy constraints with a large rank lattice and only wants to compute 1 Hecke operator (and thereby compute the genus along the way).  

I looked at computeGenusRepsAt and it seems like we could pass a vararg to allow this?

**Comment by assaferan** [comment]
It's not that simple, the main issue being function/procedure requirements (usually Hecke operator and its subroutines do not change the objects), but I have written the intrinsic HeckeOperatorAndGenus that does that, until I will be able to figure out how to merge them into a single function with a flag. Currently on branch develop, you can check it out.

**Comment by assaferan** [comment]
Hi John, this is now resolved, I believe. The varargs was added to the HeckeOperator function instead.
We can now run

>  HeckeOperator(M, p : Genus);

to compute the genus on the fly.
